service: addis-software

# Setting up out provider with Nodejs runtime 14.x
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
